# Generated by Django 3.2 on 2021-11-08 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запису на прийом')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('contact', models.CharField(max_length=100, verbose_name='Контакт')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вартість')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Контакт')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('clients', models.ManyToManyField(blank=True, to='cashbox.Client', verbose_name='Клієнти')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковий номер')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведення сеансу')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashbox.appointment', verbose_name='Запис на прийом')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashbox.client', verbose_name='Клієнт')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashbox.service', verbose_name='Процедура')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashbox.specialist', verbose_name='Фахівець')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сума')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cashbox.session', verbose_name='Сеанс')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сума')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операції')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashbox.specialist', verbose_name='Фахівець')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashbox.client', verbose_name='Клієнт'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashbox.service', verbose_name='Процедура'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashbox.specialist', verbose_name='Фахівець'),
        ),
    ]
